### ISSUE TITLE
font-size

### ISSUE THREAD

**Issue by matbech** [tyleruebele/details-shim#1]
You probably don't want to use a fixed size for the black right pointing triangle:
details.closed > summary:before {display: inline-block; content: "\25b6"; padding: 0 0.1em; margin-right: 0.4em; ~~font-size: 0.9em;~~}

**Comment by tyleruebele** [comment]
It behaves relatively (that is, not fixed) for me.  Exactly what issue are you experiencing with the `em` unit styling?

**Comment by matbech** [comment]
The unit looks correct. I fail to remember what browser under what condition (quirks mode etc) didn't like the font size for the inline content. I guess 1.5 years later it is no longer / less relevant.
