### ISSUE TITLE
IE8 addEventListener Not Supported

### ISSUE THREAD

**Issue by syntactic-salt** [tyleruebele/details-shim#2]
On line 67 of details-shim.js you call Summary.addEventListener. This throws an error in IE8 since it is not supported. You need to use attachEvent like you did on line 136. Maybe wrap the click event in an if/else block similar to when you call init at the end of the script.

**Comment by tyleruebele** [comment]
Thank you for the report.  I'll get the fix posted when I can get it tested in IE8.

**Comment by tyleruebele** [comment]
Strangely, It's not working at all for me in IE8 anymore (tested via Edge developer tools).  Are you testing with Edge or with actual IE8?

**Comment by syntactic-salt** [comment]
I'm using actual IE8. It throws an error about the object not supporting addEventListener, which IE8 does not support as you likely know.

**Comment by tyleruebele** [comment]
I can't get to actual IE8, and Edge's simulation of it isn't compatible at all.  The suggested revision is in the issue-2 branch: https://github.com/tyleruebele/details-shim/blob/issue-2/details-shim.js  Does it work for you?

**Comment by syntactic-salt** [comment]
I tested this out in native IE8 and it works like a charm.

**Comment by tyleruebele** [comment]
Thanks!  I've pushed the revision to master.
