### ISSUE TITLE
firefox needs summary {display: list-item}

### ISSUE THREAD

**Issue by gperciva** [tyleruebele/details-shim#3]
Thanks for this shim!

May I suggest using

    summary {display: list-item}

in the .css?  Otherwise, modern firefox loses the triangle:

> The default style for `<summary>` is display:list-item per HTML standard.  If the style is being changed to display:block, the disclosure triangle will be dismissed, which is expected. See Bug 1283989 for more information.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary#Usage_notes

**Comment by Mouvedia** [comment]
so instead of
```
details, summary {display: block;}

details.details_shim_closed > summary {display: block;}
details.details_shim_open   > summary {display: block;}
```
you are proposing
```
details {display: block;}
summary,
details.details_shim_closed > summary,
details.details_shim_open   > summary {
    display: block;
    display: list-item;
}
```
?

**Comment by gperciva** [comment]
Hmm... I'm a relatively novice to CSS, and complete beginner to shims, so I can't honestly say that I understand what the ` > summary` part does.  In fact, I didn't even notice them!  (I was using at the `.min.css` version)

All I personally did was change:
```
details, summary {display: block;}
```
into:
```
details {display: block;}
summary {display: list-item;}
```
and then it worked on Firefox 50, where previously it didn't display the triangle.

**Comment by tyleruebele** [comment]
Thank you for this. 

I applied your fix and verified it resolves the missing decorative triangle in current FF.  I also added classes to all my CSS selectors so my styles only affect browsers that don't natively support details.

I'll merge this into master after I have a peer test it.  Let me know if you find any problems with this fix.

**Comment by tyleruebele** [comment]
Thanks for your input.  I took your changes and @Mouvedia's suggestion, and cleaned up the demo a bit.  Also updated the README to be more clear about IE7 not working.

**Comment by tyleruebele** [comment]
OK, I think this last single commit will resolve the issue.

**Comment by gperciva** [comment]
Agreed, works on all browsers I tested with.  Thanks!
