### ISSUE TITLE
CDN? NPM?

### ISSUE THREAD

**Issue by shimmichanga** [tyleruebele/details-shim#8]
First off, amazing fix :) Edge still doesn't support details/summary in 2017, so this shim is still incredibly useful.

Is this library available on a CDN or on NPM? Right now I'm using http://rawgit.com/ but it would be nice to have a package on NPM that can be used with webpack.  One upside with NPM is immediate CDN access via https://unpkg.com/

**Comment by tyleruebele** [comment]
Thanks for reminding me Edge remains less than cutting.  We were just discussing whether we still needed to use this shim.  Clearly we do.

I have not yet submitted this to any CDN or package manager, but I'd be happy to look into it.

I'll update here if I get that set up.

**Comment by shimmichanga** [comment]
http://caniuse.com/details/embed/ 83.31% usage of browsers that do support Details/Summary so it may not be important to support Edge / IE.  In any case, thanks in advance for looking into this!

**Comment by tyleruebele** [comment]
I added this to npmjs.org at https://www.npmjs.com/package/ok-details
